name = "GL"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GL"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "pdl"
git = "https://github.com/m4lvin/lean4-pdl.git"
rev = "v4.28.0"

[[lean_lib]]
name = "GL"
